"""Update User model: align fields with auth schemas

Revision ID: 1044f7a8ec9c
Revises: e1597a1e7b29
Create Date: 2025-11-10 11:54:44.719652

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1044f7a8ec9c"
down_revision: str | Sequence[str] | None = "e1597a1e7b29"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("full_name", sa.String(length=255), nullable=True))
    op.add_column(
        "users", sa.Column("currency", sa.String(length=3), nullable=False, server_default="USD")
    )
    op.add_column(
        "users", sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true())
    )
    op.drop_column("users", "name")
    op.drop_column("users", "date_format")
    op.drop_column("users", "base_currency")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("base_currency", sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("date_format", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users", sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    op.drop_column("users", "is_active")
    op.drop_column("users", "currency")
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###
