"""Create financial_institutions table and add FK to accounts

Revision ID: 3e79c4a05b1d
Revises: cf0154ea9556
Create Date: 2025-11-19 22:57:42.019385

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e79c4a05b1d"
down_revision: str | Sequence[str] | None = "cf0154ea9556"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financial_institutions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_user_institution_name"),
    )
    op.create_index(
        op.f("ix_financial_institutions_id"), "financial_institutions", ["id"], unique=False
    )
    op.add_column("accounts", sa.Column("financial_institution_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "accounts",
        "financial_institutions",
        ["financial_institution_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "accounts", type_="foreignkey")
    op.drop_column("accounts", "financial_institution_id")
    op.drop_index(op.f("ix_financial_institutions_id"), table_name="financial_institutions")
    op.drop_table("financial_institutions")
    # ### end Alembic commands ###
