"""Add account_reconciliations table

Revision ID: 988999a9ba36
Revises: 9b289416089d
Create Date: 2025-11-11 17:58:13.811748

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "988999a9ba36"
down_revision: str | Sequence[str] | None = "9b289416089d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_reconciliations",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("reconciliation_date", sa.Date(), nullable=False),
        sa.Column(
            "expected_balance",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
            comment="Balance calculated by system",
        ),
        sa.Column(
            "actual_balance",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
            comment="Actual balance from bank/user",
        ),
        sa.Column(
            "difference",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
            comment="actual_balance - expected_balance",
        ),
        sa.Column(
            "adjustment_transaction_id",
            sa.Integer(),
            nullable=True,
            comment="Adjustment transaction created to fix difference",
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["adjustment_transaction_id"], ["scheduled_transactions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_reconciliations_account_id"),
        "account_reconciliations",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_reconciliations_id"), "account_reconciliations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_account_reconciliations_user_id"),
        "account_reconciliations",
        ["user_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("uq_exception_transaction_date"), "scheduled_transaction_exceptions", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_exception_transaction_date"),
        "scheduled_transaction_exceptions",
        ["scheduled_transaction_id", "exception_date"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_account_reconciliations_user_id"), table_name="account_reconciliations")
    op.drop_index(op.f("ix_account_reconciliations_id"), table_name="account_reconciliations")
    op.drop_index(
        op.f("ix_account_reconciliations_account_id"), table_name="account_reconciliations"
    )
    op.drop_table("account_reconciliations")
    # ### end Alembic commands ###
