"""Add ScheduledTransaction and ScheduledTransactionException models

Revision ID: 9b289416089d
Revises: 1044f7a8ec9c
Create Date: 2025-11-10 18:20:35.831906

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b289416089d"
down_revision: str | Sequence[str] | None = "1044f7a8ec9c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_transactions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("to_account_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("is_recurring", sa.Boolean(), nullable=False),
        sa.Column(
            "recurrence_frequency",
            sa.Enum("MONTHLY", "YEARLY", name="recurrencefrequency"),
            nullable=True,
        ),
        sa.Column("recurrence_day_of_month", sa.Integer(), nullable=True),
        sa.Column("recurrence_month_of_year", sa.Integer(), nullable=True),
        sa.Column("recurrence_start_date", sa.Date(), nullable=False),
        sa.Column("recurrence_end_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name="check_amount_positive"),
        sa.CheckConstraint(
            "recurrence_day_of_month IS NULL OR (recurrence_day_of_month BETWEEN -1 AND 31)",
            name="check_day_of_month_range",
        ),
        sa.CheckConstraint(
            "recurrence_end_date IS NULL OR recurrence_end_date >= recurrence_start_date",
            name="check_end_date_after_start",
        ),
        sa.CheckConstraint(
            "recurrence_month_of_year IS NULL OR (recurrence_month_of_year BETWEEN 1 AND 12)",
            name="check_month_of_year_range",
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["to_account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduled_transactions_account_id"),
        "scheduled_transactions",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_transactions_id"), "scheduled_transactions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_transactions_user_id"),
        "scheduled_transactions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "scheduled_transaction_exceptions",
        sa.Column("scheduled_transaction_id", sa.Integer(), nullable=False),
        sa.Column("exception_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount IS NULL OR amount > 0", name="check_exception_amount_positive"),
        sa.ForeignKeyConstraint(
            ["scheduled_transaction_id"], ["scheduled_transactions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "scheduled_transaction_id", "exception_date", name="uq_exception_transaction_date"
        ),
    )
    op.create_index(
        op.f("ix_scheduled_transaction_exceptions_id"),
        "scheduled_transaction_exceptions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_transaction_exceptions_scheduled_transaction_id"),
        "scheduled_transaction_exceptions",
        ["scheduled_transaction_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_scheduled_transaction_exceptions_scheduled_transaction_id"),
        table_name="scheduled_transaction_exceptions",
    )
    op.drop_index(
        op.f("ix_scheduled_transaction_exceptions_id"),
        table_name="scheduled_transaction_exceptions",
    )
    op.drop_table("scheduled_transaction_exceptions")
    op.drop_index(op.f("ix_scheduled_transactions_user_id"), table_name="scheduled_transactions")
    op.drop_index(op.f("ix_scheduled_transactions_id"), table_name="scheduled_transactions")
    op.drop_index(op.f("ix_scheduled_transactions_account_id"), table_name="scheduled_transactions")
    op.drop_table("scheduled_transactions")
    # ### end Alembic commands ###
